### PR TITLE
interchange: counter: testing on multiple boards

### PR DESCRIPTION
**Pull request by acomodi**
This PR is to enable the counter test for multiple boards.
It also fixes the port locations to LED pads for the arty test.

I have encountered an problem with the arty35 test for which the DCP was correctly generated, but it presented some unrouted nets due to some of the cells resulting to be `UNPLACED`.

### CODE REVIEW

**Comment by acomodi** [comment]
These are warnings output when opening the DCP and, in particular, `SLICE_X84Y115` is indeed the SLICE with all the unpleced BELs.

```
Parsing XDC File [/data/interchange/nextpnr/build/fpga_interchange/examples/tests/counter/counter_arty100t/null.xdc]
Finished Parsing XDC File [/data/interchange/nextpnr/build/fpga_interchange/examples/tests/counter/counter_arty100t/null.xdc]
Reading XDEF placement.
Reading placer database...
CRITICAL WARNING: [Constraints 18-4518] Instance $abc$2059$auto$blifparse.cc:498:parse_blif$2093 had Lib Cell Type INV which is different than LUT1.
CRITICAL WARNING: [Constraints 18-4522] Instance $abc$2059$auto$blifparse.cc:498:parse_blif$2093 had Lib Cell Type INV which is different than LUT1.
CRITICAL WARNING: [Constraints 18-4522] Instance $abc$2059$auto$blifparse.cc:498:parse_blif$2093 had Lib Cell Type INV which is different than LUT1.
CRITICAL WARNING: [Constraints 18-4525] Site SLICE_X84Y115 of SiteType SLICEM found to have 6 placed instances but we read indicates it has 7 placed instances.
CRITICAL WARNING: [Designutils 20-2070] During XDEF restore, placement information for 1 sites failed to restore.  Please run placement and routing to complete implementation.
```

**Comment by litghost** [comment]
Are you sure the remap is being done?

**Comment by litghost** [comment]
> Are you sure the remap is being done (INV -> LUT1)?

Bug is here: https://github.com/YosysHQ/nextpnr/blob/ec98fee1eefd61d17ccfaf58bae72e1cc0f9e5e3/fpga_interchange/examples/tests.cmake#L332-L340

If `techmap` is supplied to `add_interchange_group_test`, it isn't supplied to the inner call to `add_interchange_test`.

**Comment by acomodi** [comment]
@litghost Indeed, adding the techmap solved the issue. I have verified the counter to be working on HW on both arty 35t and 100t

**Review by gatecat — APPROVED** [review]
LGTM - seems the non-interchange CI failure was just a random glitch and I've requested a re-run

**Comment by litghost** [comment]
@gatecat This can be merged?

**Pull request merged**
