### PR TITLE
CMake: promote bba to a true subproject

### PR DESCRIPTION
**Pull request by whitequark**
The direct motivation for this change is better cross-builds: since the only thing I actually *want* from the native build is bba (and everything else just gets in the way), bba can and should be its own subproject, which can be independently configured and built with CMake. Non-cross builds are not affected.

I also took the liberty to clean up the bba CMake files, since they were using some really ancient style.

### CODE REVIEW

**Comment by whitequark** [comment]
cc @daveshah1 @mmicko

**Comment by whitequark** [comment]
Actually, I think I didn't get the scoping quite right, I need to amend this.

**Comment by mmicko** [comment]
LGTM as well

**Comment by whitequark** [comment]
PTAL, I changed the approach slightly. It is now cleaner and also actually works for cross-builds.

**Pull request merged**
