### PR TITLE
Update README with workaround for "cannot find -lpthreads"

### PR DESCRIPTION
**Pull request by gojimmypi**
I encountered this error again on WSL Ubuntu 20.04 and despite seemingly having all dependencies installed, `find /lib -name "*pthread*" ` does not return any results. (This is not a problem on my 
Ubuntu WSL 18.04).

However, the [workaround for #215](https://github.com/YosysHQ/nextpnr/issues/215#issuecomment-456053526) seemed to work. 

I've updated the README with info on the workaround.

### CODE REVIEW

**Comment by whitequark** [comment]
Is there an open bug for this problem on WSL 20.04 so that it can be tracked and hopefully fixed? Stuffing a workaround into README feels like sweeping problems under the carpet.

**Comment by daveshah1** [comment]
What is the actual problem anyway? I think the pthread error in that other issue might have been a red herring and the actual issue was boost related.

**Comment by gojimmypi** [comment]
@whitequark I didn't open a new issue... I thought perhaps it is just WSL related and a workaround exists. Would you like me to open a new issue?

@daveshah1 I am seeing a new `cannot find -lpthreads` error at compile time in a fresh Ubuntu 20.04 WSL that I do not see in 18.04, despite having  (what I believe to be)  all the dependencies installed.

I'm working on a ["bare bones" install](https://github.com/gojimmypi/ulx3s-toolchain/blob/master/install_barebones.sh) for the FPGA build/synthesis from within Visual Studio. The specific install script I have for nextpnr is [here](https://github.com/gojimmypi/ulx3s-toolchain/blob/master/install_nextpnr.sh).

**Comment by whitequark** [comment]
> I thought perhaps it is just WSL related and a workaround exists. Would you like me to open a new issue?

A workaround helps people who were blocked by the issue enough to go over README again. A fix in the build system helps everyone. Shouldn't we prefer the latter?

**Comment by gojimmypi** [comment]
Yes, I certainly agree it is good to have a robust build system to help everyone. Still, some part of me still would like to have the knowledge available for the workaround. 

I've created https://github.com/YosysHQ/nextpnr/issues/444 with the details.

**Comment by whitequark** [comment]
AFAICT the error in #444 has nothing to do with nextpnr, at least not directly; your system is running out of memory and the compiler is handling that badly.

**Comment by gojimmypi** [comment]
@whitequark you are quite correct. [Low memory](https://github.com/YosysHQ/nextpnr/issues/444#issuecomment-630886150) was the root cause.

> Stuffing a workaround into README feels like sweeping problems under the carpet

I completely agree. I'll come up with something to instead warn about low memory.

**Pull request closed without merging**
