### PR TITLE
fix clang complaint on turbofish

### PR DESCRIPTION
**Pull request by aep**

### CODE REVIEW

**Comment by daveshah1** [comment]
Thanks, I'll merge once the CI goes green as a double check

**Comment by whitequark** [comment]
This shouldn't be necessary on C++11 and later. What's the error?

**Comment by aep** [comment]
```
[ 50%] Building CXX object CMakeFiles/bbasm.dir/main.cc.o
/Users/aep/kram/nextpnr/bba/main.cc:89:69: error: a space is required between consecutive right angle brackets (use '> >')
    options.add_options()("files", po::value<std::vector<std::string>>(), "file parameters");
                                                                    ^~

```

**Comment by daveshah1** [comment]
Oh, maybe the C++ standard isn't being set correctly in the bbasm cmake

**Comment by aep** [comment]
oh yeah, im building each thing separate because i dont understand how to make cmake find dependencies, so that could be causing the issue

**Comment by whitequark** [comment]
Add this to CMakeLists:
```
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED YES)
```

**Pull request closed without merging**
