### PR TITLE
PLL GB usage and placement fix

### PR DESCRIPTION
**Pull request by smunaut**

### CODE REVIEW

**Comment by daveshah1** [comment]
Can you have a look at the regression test failure for issue0127? Otherwise LGTM

**Comment by smunaut** [comment]
Yup looking at it now

**Comment by smunaut** [comment]
Yeah there is definitely something wrong with the second patch :/

**Comment by smunaut** [comment]
Fixed now. If there is a unused net connected to one of the global output, it now gets removed.

**Pull request merged**
