### PR TITLE
ecp5: IOLOGIC improvements

### PR DESCRIPTION
**Pull request by daveshah1**
This implements most of the missing IOLOGIC features, in particular:

 - 7:1 gearboxes (ODDR71B and IDDR71B)
 - IO (and tristate) flip flops, using the `syn_useioff` attribute (same as Diamond) to enable packing a TRELLIS_FF into the IOLOGIC. Tristate flip flops can be combined with output DDR
 - ECLKBRIDGECS for edge clocks that span the chip

See SymbiFlow/prjtrellis#107

### CODE REVIEW

**Comment by whitequark** [comment]
This is extremely nice!

**Comment by whitequark** [comment]
How is the combination of a IODDRX1F for i/o and OFS1P3DX for OE handled?

**Comment by daveshah1** [comment]
It will be packed unless there is a mismatch between clock or reset signal; then it would be an error.

**Comment by whitequark** [comment]
Excellent. I have an option of packing an SDR or DDR register into OE site, right?

**Comment by daveshah1** [comment]
Only an SDR one, I'm not sure if DDR tristate (outside of memory DQS mode) is even supported by hardware

**Comment by whitequark** [comment]
Ah OK. It's interesting that some vendors support it and some do not. Looks like Xilinx and Altera do.

**Pull request merged**
