### PR TITLE
Nexus: Fixed OSCA parameters, add pll default parameters

### PR DESCRIPTION
**Pull request by mtdudek**
This PR adds default parameters to PLL cell in nexus.
Without this change bitstream generated using prjoxide does not work.

Signed-off-by: Maciej Dudek <mdudek@antmicro.com>

### CODE REVIEW

**Comment by gatecat** [comment]
I must admit I'd rather not go this route given the possibilities of subtle changes in behaviour, so you'll have to define any defaults you care about in `bitstream.cc`.

**Comment by mtdudek** [comment]
@gatecat I hope this is better

**Comment by gatecat** [comment]
Sorry, had a bit of a backlog to deal with, I'll try and get a review of this & the prjoxide stuff done over the next few days...

**Comment by mtdudek** [comment]
@gatecat  I've removed temporary cell. i hope now it's good to go.

**Pull request merged**
