### PR TITLE
himbaechel: Fix for Python 3.9

### PR DESCRIPTION
**Pull request by gatecat**
@yrabbit can you confirm this is enough to make it work for you?

### CODE REVIEW

**Comment by yrabbit** [comment]
check in three hours

**Comment by yrabbit** [comment]
oh, there are still problems with my computer - unfortunately I won’t be able to check it until the weekend;(

**Comment by gatecat** [comment]
It seems to run fine with a local install of Python 3.9; still, let me know if you hit any further problems.

**Comment by yrabbit** [comment]
The apicula examples (which build the nextpnr master branch) have compiled. There is a very high probability that everything will be fine.

**Pull request merged**
