### PR TITLE
Add missing part of PR #933

### PR DESCRIPTION
**Pull request by whitequark**
Not sure how I missed this before, sorry.

### CODE REVIEW

**Comment by gatecat** [comment]
Do you think there'd be value in checking that it builds for wasm as part of the nextpnr CI?

**Comment by whitequark** [comment]
That would be nice!

**Comment by gatecat** [comment]
I need to look into tidying up the current split between GH actions and Cirrus, and I'll see if I can add that at the same time.

**Comment by whitequark** [comment]
Thank you~

**Pull request merged**
