### PR TITLE
gowin: support for locales other than en_US and C

### PR DESCRIPTION
**Pull request by yrabbit**
Specifically, those locales where the fractional part separator in
floating point numbers is not a period.

Signed-off-by: YRabbit <rabbit@yrabbit.cyou>

### CODE REVIEW

**Comment by gatecat** [comment]
Looking at CI this is failing with `what():  locale::facet::_S_create_c_locale name not valid`. If you can fix that, this should then be applied to all arches - probably in `CommandHandler`.

**Comment by yrabbit** [comment]
Apparently this happens because the ubuntu test image does not have locale support installed. I think I can detect such a case and do something reasonable, but I would have to use this CI a couple of times to debug it (it would be faster than if I downloaded and installed an ubuntu distribution somewhere). 
Is this acceptable?

**Comment by gatecat** [comment]
Yeah, that sounds reasonable to me

**Comment by yrabbit** [comment]
Great. I think it works.
I don't know about the other tests, but ubuntu no longer swears at the locale:)

**Pull request merged**
