### PR TITLE
cmake: Disable building GUI by default

### PR DESCRIPTION
**Pull request by daveshah1**
Following large numbers of [GUI-related issues](https://github.com/YosysHQ/nextpnr/issues?q=is%3Aissue+qt5), it seems like disabling the GUI by default is going to be the path of least resistance, given that the command line flow is what most people are primarily using.

### CODE REVIEW

**Review by mmicko — APPROVED** [review]
LGTM

**Review by whitequark — COMMENTED** [review]
There's more references to Qt packages in sample command lines in README—I would personally split that section into two.

**Comment by daveshah1** [comment]
> There's more references to Qt packages in sample command lines in README—I would personally split that section into two.

Updated, how do you think it looks now?

**Review by whitequark — APPROVED** [review]
Very nice!

**Comment by mithro** [comment]
BTW - We ship separate `nextpnr` and a `nextpnr-gui` GUI packages for this exactly this reason.

**Pull request merged**
