### PR TITLE
router2: fix 8935c186

### PR DESCRIPTION
**Pull request by Ravenslofty**

### CODE REVIEW

**Comment by whitequark** [comment]
Thanks!

**Comment by whitequark** [comment]
Looks like the fix doesn't work: https://github.com/YoWASP/nextpnr/actions/runs/5273760173/jobs/9537541164

**Comment by Ravenslofty** [comment]
Then I'm not sure what to do.

**Comment by gatecat** [comment]
You could just use the value via C++ numeric_limits (as generally used elsewhere in nextpnr) instead, perhaps with a helper constant somewhere.

**Comment by gatecat** [comment]
@Ravenslofty ping?

**Pull request merged**
