### PR TITLE
When choosing between labels for one net, always prefer ports

### LINKED ISSUE #280: Warning: net 'x' does not exist in design, ignoring clock constraint
The net (`clk12_0__i` in this case; [repro.zip](https://github.com/YosysHQ/nextpnr/files/3220488/repro.zip)) is definitely in the design, I can see it in the JSON file. In fact it is a toplevel port.

I think there are 2 nextpnr issues here:
  * nextpnr ignores impossible to apply clock constraint and proceeds (this should fail by default, like not passing timing was changed to fail recently);
  * nextpnr somehow loses the net.

### PR DESCRIPTION
**Pull request by whitequark**
1. Ports are already used in PCF and LPF files, so it is natural
that the developer would use them for constraints as well.
(Actually I think currently the LPF FREQUENCY PORT constraint
doesn't work correctly.)

2. Unpredictable (the set of netlabels nextpnr looks at depends on
the optimizations during synthesis) net naming makes it impossible
for code generators like nMigen to reliably apply clock constraints.

Fixes #280.

### CODE REVIEW

**Comment by daveshah1** [comment]
Thanks, agree with this change. Will merge once CI goes green.

**Comment by whitequark** [comment]
This is a test bug. Test relies on unspecified behavior.
```patch
diff --git a/ice40/regressions/issue0084/mlaccel.sh b/ice40/regressions/issue0084/mlaccel.sh
index a0074be..76dfd09 100644
--- a/ice40/regressions/issue0084/mlaccel.sh
+++ b/ice40/regressions/issue0084/mlaccel.sh
@@ -1,3 +1,3 @@
 :> mlaccel.log
 ${NPNR} --json mlaccel.json --asc mlaccel.asc --pcf mlaccel.pcf `cat mlaccel.npnr` > mlaccel.log 2>&1 || true
-grep "^ERROR: PACKAGE_PIN of SB_IO 'qpi_in_buf\\[1\\]' connected to more than a single top level IO.$" mlaccel.log
+grep "^ERROR: PACKAGE_PIN of SB_IO 'qpi_in_buf\\[[01]\\]' connected to more than a single top level IO.$" mlaccel.log

```

**Comment by daveshah1** [comment]
Thanks, applied patch to nextpnr-tests upstream 5182fd4. Can you bump the tests submodule in your PR to include this?

**Comment by whitequark** [comment]
@daveshah1 Done

**Pull request merged**
